{{- if .Values.webhook.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webhook
  labels:
    app: {{ .Chart.Name }}
    component: webhook
    chart: {{ template "_chart.label" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  sessionAffinity: None
  type: ClusterIP
{{ end }}